#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@alist[-1]
	add ucitrack alist
	set ucitrack.@alist[-1].init=alist
	commit ucitrack
EOF

rm -rf /tmp/luci-*
chmod 755 /etc/init.d/alist
exit 0
